import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Sidebar from '@/components/Sidebar/Sidebar'
import FloatingPlayer from '@/components/Footer/FloatingPlayer'
import { ContextProvider } from '@/contexts/ContextProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <ContextProvider>
          <body className={inter.className}>
            <div className='w-full flex'>
                <Sidebar />
                <div className='w-full bg-woman-in-black bg-contain bg-right bg-no-repeat flex flex-col z-10 overscroll-none max-h-screen h-screen overflow-y-hidden'>
                  <Navbar />  
                      {children}
                  <FloatingPlayer />
                </div>
              </div>
          </body>
        </ContextProvider>
    </html>
  )
}
